name: eBPF CI

on:
  push:
    branches: [ebpf]
  pull_request:
    branches: [ebpf]

jobs:
  build-bpftool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
    
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev zlib1g-dev llvm clang lld
    
      - name: Build bpftool
        run: |
            cd bpftool/src
            make
            echo "$(pwd)" >> $GITHUB_PATH
  build-ebpf-sketch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          generator: Ninja
          source-dir: .
          build-dir: build