name: eBPF CI

on:
  push:
    branches: [ebpf]
  pull_request:
    branches: [ebpf]

jobs:
  build-bpftool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
    
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev zlib1g-dev llvm llvm-dev clang lld
    
      - name: Build bpftool
        run: |
            cd bpftool/src
            make
            echo "$(pwd)" >> $GITHUB_PATH

      - name: Upload bpftool artifact
        uses: actions/upload-artifact@v4
        with:
          name: bpftool
          path: bpftool/src/bpftool

  build-ebpf-sketch:
    runs-on: ubuntu-latest
    needs: build-bpftool
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          sudo apt-get install -y libelf-dev zlib1g-dev clang-20 llvm-20 llvm-20-dev lld-20 libbpf-dev ninja-build
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 200
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 200
          sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-20 200
          sudo update-alternatives --install /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-strip-20 200
          sudo update-alternatives --install /usr/bin/lld lld /usr/bin/lld-20 200

      - name: Download bpftool artifact
        uses: actions/download-artifact@v4
        with:
          name: bpftool
          path: bpftool-bin

      - name: Add bpftool to PATH
        run: |
          chmod +x bpftool-bin/bpftool
          echo "$(pwd)/bpftool-bin" >> $GITHUB_PATH

      - name: Verify clang version
        run: |
          clang --version
          llvm-config --version

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          generator: Ninja
          source-dir: .
          build-dir: build